spring.application.name=veterinaria
server.port=8081

# Configuración de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dbveterinaria_final_in5am?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
